language: python
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
install: pip install -r requirements.txt
script:
- python setup.py install
- cd tests/
- py.test
- cd ..
notifications:
  slack:
    secure: VGS72UVO50LQpRshKjCxFaAZ53URGDdYf6YBz2RsGeeXxB0pinNcBCI3z8jTFrkqqMxXFDcyiyPPfW2iQ/yv/1QM6IonL/bZlfr6nfQqGzArNev3cBQVE6Q4/MFhiQUWnKJP6ofLRVW80n7X/5ko2ry+3HN6yk/43WrBVug1KwfEjcrCJlQ7kxJWTWYfmJxpJe6nVEM6ckh4qq18K7lOXyCoMnowSc3dJFIKA2JFU3zCwpk9ProoTPDR9hiGcQ+oREQbcgFZrwfMm3Itpse1QXNZbeF8uhVV430YGF+ULI2C1K44lvl5wq1FQ1BIsyLGxKPTVqA0dr9MUeYc+lnomBp/1ePAMGoYlMNkpAZJyLqw0Vv0e7WIaWbdACFw4pUOkKkO3nfQB2JITARV+G2gIJ3tPPY5jOjhw5QSnY/xFoXWgBfQ/88ZtFtJu6Zot4UwjxrHM/iVya1BLwI7h2/w6Swp19nWxIUnx1OG3uR4QoW0eF4Wxfxq1zgMvjQiuJKJO9OFepKMexvAc5YLwtUmm8C8njMKYrcdfu7iifE9Jc83PXGRSsZi9kxumbJuDGsdkxRIHPPs8glm4jSuwyvBFfkdBfPcrGtfYHqJWCLJP20icOrjil46NJoKRanfAOyWQja8JX/fZYzyPSFfV2/sgXr2i7NBIa7Vlacr2iVWD0g=
deploy:
- provider: pypi
  user: EeOneDown
  password:
    secure: sbecpA2+gGLRWDr9cwVfGqcY2j+G7L5CkflKGcQ9DCqJL+63tvRt875Ch3P+Ty4ADuP2q2TNd3KZKsyVzZQcCfZWlUuRL9VOTcj/vRhwEAJiI2cQ8f4eq/Qqu6E6e2IJRK0zDM48djurBylUdM0qPaf6wQ3rXorYMlbUotZNg0gFlIPKhIaGZQ0XaxiUKxK/T7qTuVQxpDGhk2yDJCXusMP2zA7d2UAwUxcs0HMIbr4EeZvMpcdubSa/ZPKmPpgx3Gf7Ttf5KcsjSHK9kdlQUjEullmnmUithZPRIpXnrJFoDWo9l+n09E3Ov3jc9nL0TLws8XeZLQ3dMZrgD4gy2MkSzTYAz0zlB4XkOwu3NieV044je92fSwwfhvuv7Ig6C2MXCtks23WMi+X4R59Pm7Vq0EJu0/xxhxaVuvk4assrvP+q3wD/Ocac9lTSPpeGJr4IM2pLdr1iWxxG2kqGuz+imWk4d6kn4q0mtX5TWaJv6oMb3Lgne7m6WMuIWkpe32c/uT26sjAuGuuWjFq6UsKVVxQYSe6Cf+YnScA4a95fBoEXNj+n8vh9c1qPBoH811t3aAKF0jTznYRMB7YgZMznQ2tFuLpWSU1CvKovsxodOky1k2h7Yp5YX5qQHrppC7GgoaCBxXvkDv6nD2KmTWoHodc6C2NR4qFnKmLbq2k=
  on:
    tags: true
    python: 3.7
    repo: EeOneDown/spbuTimetableAPI
