language: python
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
install: pip install -r requirements.txt
script:
- python setup.py install
- cd tests/
- py.test
- cd ..
deploy:
- provider: pypi
  user: EeOneDown
  password:
    secure: sbecpA2+gGLRWDr9cwVfGqcY2j+G7L5CkflKGcQ9DCqJL+63tvRt875Ch3P+Ty4ADuP2q2TNd3KZKsyVzZQcCfZWlUuRL9VOTcj/vRhwEAJiI2cQ8f4eq/Qqu6E6e2IJRK0zDM48djurBylUdM0qPaf6wQ3rXorYMlbUotZNg0gFlIPKhIaGZQ0XaxiUKxK/T7qTuVQxpDGhk2yDJCXusMP2zA7d2UAwUxcs0HMIbr4EeZvMpcdubSa/ZPKmPpgx3Gf7Ttf5KcsjSHK9kdlQUjEullmnmUithZPRIpXnrJFoDWo9l+n09E3Ov3jc9nL0TLws8XeZLQ3dMZrgD4gy2MkSzTYAz0zlB4XkOwu3NieV044je92fSwwfhvuv7Ig6C2MXCtks23WMi+X4R59Pm7Vq0EJu0/xxhxaVuvk4assrvP+q3wD/Ocac9lTSPpeGJr4IM2pLdr1iWxxG2kqGuz+imWk4d6kn4q0mtX5TWaJv6oMb3Lgne7m6WMuIWkpe32c/uT26sjAuGuuWjFq6UsKVVxQYSe6Cf+YnScA4a95fBoEXNj+n8vh9c1qPBoH811t3aAKF0jTznYRMB7YgZMznQ2tFuLpWSU1CvKovsxodOky1k2h7Yp5YX5qQHrppC7GgoaCBxXvkDv6nD2KmTWoHodc6C2NR4qFnKmLbq2k=
  on:
    tags: true
    python: 3.7
    repo: EeOneDown/spbuTimetableAPI
notifications:
  slack:
    secure: LfEMTnbIpWIMMOIwslyfOzSOxm6rWQdlTdGe5WkWHaLlPBWYFeo7bDWERujnSw7IWp15a93Uh2ivAxZ+zxgJGSe7icfT3cLdwd/SjSnFn6LuXoE4Y5jus0CTeTmyeYdHYkCFjk4ZuqPsn8MKCkMWXepqpEsS4I+qOML8o2gKtZB8ve53bOXVeFvupLpvld1S79LqUivvOTVnUA6qyECfVCpoVFuw3A/NroIAJxgHo/ThLdE+XJbg55GUhMu1NIdT96dkRGQuTMV04poPE10GS4LUE5OKkLdl6Penj0h9M4UaCBP19UNJ3RNS3v5FouNiL3oDvNUTBxu+T+7tf7aQr8DNk4uRLKKwq+dOrI2hfCqZ7GlA0AliKfwmi4CKATiKy4JKX68m9318GLZzNLj+mAycttGm2IJQxZe53CAVSihlCtkCz4nyteq9Qi/cEEP9p2brnTNcN03yivAraMm0/t2L0PBh39hzBV5wtwH7tMIW5kwpt3BIBqld1B/+yyXxSGr9tBL/Sf/Br98uykYzgDDsiH6NQaGXH5qsIt4fi4Fi+HtgmjMvz5u0urW9AiAGqCLl7faIkEdxOLm6ywru+HXJ6PG9NfEVK5mtUl+l5ubRwDb0+vaevTUZJH3lqgZrmYZvKGXfLfox0t2rO8MpL0K8eBX2D6aEDk8GpAXqPW4=
