language: python
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
install: pip install -r requirements.txt
script:
- python setup.py install
- cd tests/
- py.test
- cd ..
deploy:
- provider: pypi
  user: EeOneDown
  password:
    secure: sbecpA2+gGLRWDr9cwVfGqcY2j+G7L5CkflKGcQ9DCqJL+63tvRt875Ch3P+Ty4ADuP2q2TNd3KZKsyVzZQcCfZWlUuRL9VOTcj/vRhwEAJiI2cQ8f4eq/Qqu6E6e2IJRK0zDM48djurBylUdM0qPaf6wQ3rXorYMlbUotZNg0gFlIPKhIaGZQ0XaxiUKxK/T7qTuVQxpDGhk2yDJCXusMP2zA7d2UAwUxcs0HMIbr4EeZvMpcdubSa/ZPKmPpgx3Gf7Ttf5KcsjSHK9kdlQUjEullmnmUithZPRIpXnrJFoDWo9l+n09E3Ov3jc9nL0TLws8XeZLQ3dMZrgD4gy2MkSzTYAz0zlB4XkOwu3NieV044je92fSwwfhvuv7Ig6C2MXCtks23WMi+X4R59Pm7Vq0EJu0/xxhxaVuvk4assrvP+q3wD/Ocac9lTSPpeGJr4IM2pLdr1iWxxG2kqGuz+imWk4d6kn4q0mtX5TWaJv6oMb3Lgne7m6WMuIWkpe32c/uT26sjAuGuuWjFq6UsKVVxQYSe6Cf+YnScA4a95fBoEXNj+n8vh9c1qPBoH811t3aAKF0jTznYRMB7YgZMznQ2tFuLpWSU1CvKovsxodOky1k2h7Yp5YX5qQHrppC7GgoaCBxXvkDv6nD2KmTWoHodc6C2NR4qFnKmLbq2k=
  on:
    tags: true
    python: 3.7
    repo: EeOneDown/spbuTimetableAPI
notifications:
  slack:
    secure: l8v/BP/EMgd/ZFVOTf+ZtlNwaXIBspUgQIG3nkqKXSbX0AvO+Q1CrvbVwidrpOBQ7yMCyjFDPjPCmxVERmzgwLHEm/DnAyap2x6mSCgLsWG8eFszxCR+8/L8Ehlk/zx29vmUj53oKmKTRvWDba0rVDhLsdvjJP5UZ+iJCmybDQHVGHEwPBrsm2HHH7pZ7AXixYR+vXHlaJ8LUg5S85C1YdIo7D3RbCbS2pXtIWY8W8Gu08mVv/28zy+XRQaUEX3lQOZPNNiIw0gmJLexVgX/avdfelzYp+osqGc3DzsARr0oToBl9xGwkOa9WMWyfuSIXvJ5F1nuQcOJyPGc2wxtxz+m1IarW50u3A5yIBgYZGIpcUXj0Fi/756MM3yGiGOmvSJ71w7eP0TPQ/u42MXdrhSN/a7Kw5PBmL7MopEfj0moPmm3/lFuCGs8eoNZxRoYT7DaP4AwY+UP+zt03rHDLSgyKZSTPZ1xb6sfQ66VyJ8srmfcZ8Z42vXT/+mnCni4rB9g3ey2+Gyb2aunA1Aclh85dddhrG7IN3SCeBv+zOXfauQEqM9uNZCizUYdkvUcQgwxNChlYC5098nE2At9C1VcE/7hJYabbtm/7ZdE/1wTi39cFmrCOycu+89sHXZc8qGqgd2WoxDnibaKmIsccUfiJI6uPDzALfbSIMnR9Yk=
